### PR TITLE
No more types genomics

### PR DESCRIPTION
**Pull request by Oddant1**
Change types_genomics to types in accordance with qiime2/q2-types#309

Blocked by qiime2/q2-types#309

### CODE REVIEW

**Review by lizgehret — APPROVED** [review]
all looks good here - will test locally before merging the blocking types PR and then CI can be re-run here for a final check.

**Comment by lizgehret** [comment]
Hey @nbokulich @gregcaporaso could one of you give me write access to this repo? I need to push up some lint fixes and re-run CI before getting this merged (Anthony is officially out for the next week on vacation).

**Comment by nbokulich** [comment]
Hi @lizgehret done! thanks @Oddant1 and @lizgehret for making these changes!

**Comment by nbokulich** [comment]
Merging this to resolve the chicken-vs-egg problem re: metapackage build. See https://github.com/bokulich-lab/q2-assembly/pull/71#issuecomment-1946429237

**Pull request merged**
